# @copyright Hidden Moss
# @see Hidden Moss: https://hiddenmoss.com/
# @see repo: https://github.com/hidden-moss/xls2gd
# @author Yuancheng Zhang, https://github.com/endaye
# 
#* source file: xls_nft.xlsx
#! THIS FILE IS GENERATED BY tool_xls2gd.py.
#! DONT'T CHANGE IT MANULLY.

const background = {
	"Light Blue Sky 01":
	{
		"id": "Light Blue Sky 01",
		"sky_color": "5fb0ba"
	},
	"Light Brown Sky 01":
	{
		"id": "Light Brown Sky 01",
		"sky_color": "e3ac98"
	},
	"Light Green Sky 01":
	{
		"id": "Light Green Sky 01",
		"sky_color": "6e9985"
	},
	"Light Green Sky 02":
	{
		"id": "Light Green Sky 02",
		"sky_color": "6e9985"
	},
	"Mid Blue Sky 01":
	{
		"id": "Mid Blue Sky 01",
		"sky_color": "525f71"
	},
	"Mid Blue Sky 02":
	{
		"id": "Mid Blue Sky 02",
		"sky_color": "525f71"
	},
	"Mid Blue Sky 03":
	{
		"id": "Mid Blue Sky 03",
		"sky_color": "525f71"
	},
	"Mid Blue Sky 04":
	{
		"id": "Mid Blue Sky 04",
		"sky_color": "525f71"
	},
	"Mid Blue Sky 05":
	{
		"id": "Mid Blue Sky 05",
		"sky_color": "525f71"
	},
	"Mid Blue Sky 06":
	{
		"id": "Mid Blue Sky 06",
		"sky_color": "255165"
	},
	"Mid Green Sky 01":
	{
		"id": "Mid Green Sky 01",
		"sky_color": "007973"
	},
	"Mid Green Sky 02":
	{
		"id": "Mid Green Sky 02",
		"sky_color": "007973"
	},
	"Mid Green Sky 03":
	{
		"id": "Mid Green Sky 03",
		"sky_color": "007973"
	},
	"Night Sky 01":
	{
		"id": "Night Sky 01",
		"sky_color": "0d2a38"
	},
	"Night Sky 02":
	{
		"id": "Night Sky 02",
		"sky_color": "0d2a38"
	},
	"Orange Sky 01":
	{
		"id": "Orange Sky 01",
		"sky_color": "db733a"
	}
}
